const facultyHashtags = {
  "Infocomm Technology": [
    "#softwareDevelopment",
    "#dataAnalysis",
    "#cloudSolutions",
    "#userExperience",
    "#mobileDevelopment",
    "#networkSecurity",
    "#machineLearning",
    "#dataScience",
    "#cyberSecurity",
    "#cloudComputing",
    "#virtualReality",
    "#augmentedReality",
    "#blockChain",
    "#userInterfaceDesign",
    "#quantumComputing",
    "#networking",
    "#embeddedSystems",
    "#webDevelopment",
    "#bigData",
    "#ecommerce",
    "#computerVision",
    "#smartCities",
    "#internetOfThings",
    "#prototyping",
    "#userResearch",
  ],
  "Food, Chemical and Biotechnology": [
    "#foodScience",
    "#qualityControl",
    "#productDevelopment",
    "#microbiology",
    "#foodTechnology",
    "#sensoryEvaluation",
    "#nutritionalScience",
    "#foodSafety",
    "#organicChemistry",
    "#materialScience",
    "#chemicalEngineering",
    "#bioChemistry",
    "#foodInnovation",
    "#flavorChemistry",
    "#fermentation",
    "#foodProcessing",
    "#productQuality",
    "#bioengineering",
    "#agritechnology",
    "#environmentalScience",
    "#biopolymers",
    "#bioprocessing",
    "#biosynthesis",
    "#foodPackaging",
    "#foodPreservation",
  ],
};

export { facultyHashtags };
