const firstNames = [
  "Jason",
  "Maria",
  "Kevin",
  "Sarah",
  "James",
  "Emily",
  "Michael",
  "Rachel",
  "David",
  "Anna",
  "Ella",
  "George",
  "Natalie",
  "Liam",
  "Sophia",
  "John",
  "Amelia",
  "Oliver",
  "Megan",
  "Noah",
  "Emma",
  "Lucas",
  "Chloe",
  "Aiden",
  "Lily",
  "Gabriel",
  "Zoe",
  "Benjamin",
  "Charlotte",
  "Ethan",
  "Ethan",
  "Olivia",
  "Daniel",
  "Harper",
  "Ava",
  "William",
  "Mia",
  "Alexander",
  "Sophia",
  "Evelyn",
  "Benjamin",
  "Amelia",
  "Logan",
  "Abigail",
  "Elijah",
  "Henry",
  "Grace",
  "Emily",
  "Oliver",
  "Charlotte",
  "Samuel",
  "Elizabeth",
  "Michael",
  "Penelope",
  "Jack",
  "Isabella",
  "Lucas",
  "Harper",
  "Aiden",
  "Madison",
  "Morgan",
  "Taylor",
  "Jordan",
  "Casey",
  "Cameron",
  "Avery",
  "Riley",
  "Alexis",
  "Peyton",
  "Quinn",
  "Jordan",
  "Harper",
  "Reese",
  "Sawyer",
  "Rowan",
  "Dakota",
  "Emerson",
  "Finley",
  "Emery",
  "Aubrey",
  "Charlie",
  "Skyler",
  "Hayden",
  "Jaden",
  "Kendall",
  "Parker",
  "Tatum",
  "Armani",
  "Blair",
  "Dallas",
  "Frankie",
  "Elliot",
  "Phoenix",
  "River",
  "Sage",
  "Shiloh",
  "Spencer",
  "Terry",
  "Jamie",
  "Leslie",
  "Micah",
  "Morgan",
  "Drew",
  "Brett",
  "Carter",
  "Devin",
  "Jessie",
  "Reagan",
  "Robin",
  "Stevie",
];

const lastNames = [
  "Ang", "Bailey", "Brooks", "Campbell", "Chan", "Chia", "Cheong", "Chen", "Chong", "Choo",
  "Collins", "Foo", "Frost", "Goh", "Heng", "Ho", "Hudson", "Hunter", "Jensen", "Kelly",
  "Kennedy", "Koh", "Kwan", "Lane", "Lau", "Lee", "Lim", "Logan", "Loh", "Low",
  "McKenzie", "Morgan", "Murphy", "Ng", "Ong", "Owen", "Pang", "Parker", "Perry", "Phua",
  "Porter", "Quek", "Ray", "Reed", "Reese", "Reid", "Riley", "Ross", "Ryan", "Russell",
  "Sanders", "Scott", "Shaw", "Shelby", "Sheridan", "Simmons", "Sloan", "Sia", "Soh", "Spencer",
  "Tan", "Tate", "Tay", "Terry", "Todd", "Toh", "Tyler", "Valentine", "Wallace", "Watts",
  "Webb", "Wells", "West", "Wilder", "Wiley", "Wong", "Winters", "Yap", "Yeo", "Yeoh"
];


export { firstNames, lastNames };
